site_name: My Kubernetes Journey
site_url: https://ERRORIK-ai.github.io/ClusterBusters/

theme:
  name: material # Doc: https://squidfunk.github.io/mkdocs-material/
  language: de
  color_mode: dark
  user_color_mode_toggle: true
  palette:
    - scheme: slate
      primary: black
      accent: black

nav:
  - Home: index.md

markdown_extensions:
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
      title: Inhaltsverzeichnis

