name: Build and Deploy MkDocs site (Pages action)

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MkDocs + theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-simple-blog

      - name: Build MkDocs site
        run: mkdocs build --config-file my-journey/mkdocs.yml

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: my-journey/site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
