name: Deploy MkDocs Site

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install mkdocs mkdocs-simple-blog

    - name: Build MkDocs site
      run: mkdocs build --config-file my-journey/mkdocs.yml

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: my-journey/site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
